<?php

/**
 * Implements hook_install().
 */
function ai_content_install() {
  module_load_install('ai_upgrade');
  ai_upgrade_module_install('ai_content');
}

/**
 * Implements hook_uninstall().
 */
function ai_content_uninstall() {
  config('ai_content.settings')->delete();
}

/**
 * Implements hook_requirements().
 */
function ai_content_requirements($phase) {
  module_load_install('ai_upgrade');
  return ai_upgrade_module_requirements($phase, 'ai_content');
}
