<?php

/**
 * Implements hook_install().
 */
function ai_privacy_install() {
  module_load_install('ai_upgrade');
  ai_upgrade_module_install('ai_privacy');
}

/**
 * Implements hook_uninstall().
 */
function ai_privacy_uninstall() {
  config('ai_privacy.settings')->delete();
}

/**
 * Implements hook_requirements().
 */
function ai_privacy_requirements($phase) {
  module_load_install('ai_upgrade');
  return ai_upgrade_module_requirements($phase, 'ai_privacy');
}
